# Generated by Django 4.1.6 on 2023-02-07 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default=datetime.date(2023, 2, 7), max_length=1000),
            preserve_default=False,
        ),
    ]
